# Generated by Django 5.2.11 on 2026-02-08 14:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('locadora_nome', models.CharField(max_length=255, verbose_name='Nome da Locadora')),
                ('locadora_cpf', models.CharField(max_length=14, verbose_name='CPF da Locadora')),
                ('locadora_rg', models.CharField(max_length=20, verbose_name='RG da Locadora')),
                ('locadora_endereco', models.CharField(max_length=255, verbose_name='Endereço da Locadora')),
                ('tenant_name', models.CharField(max_length=255, verbose_name='Nome do Locatário')),
                ('tenant_cpf', models.CharField(max_length=14, verbose_name='CPF do Locatário')),
                ('tenant_rg', models.CharField(max_length=20, verbose_name='RG do Locatário')),
                ('tenant_profession', models.CharField(max_length=100, verbose_name='Profissão do Locatário')),
                ('tenant_prev_address', models.TextField(verbose_name='Endereço Anterior do Locatário')),
                ('property_address', models.TextField(verbose_name='Endereço do Imóvel')),
                ('property_cep', models.CharField(max_length=9, verbose_name='CEP do Imóvel')),
                ('monthly_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Mensal')),
                ('payment_day', models.PositiveIntegerField(default=10, verbose_name='Dia do Pagamento')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('duration_months', models.PositiveIntegerField(default=30, verbose_name='Duração em Meses')),
                ('contract_type', models.CharField(choices=[('TIPICO', 'Típico (30 meses)'), ('ATIPICO', 'Atípico')], max_length=10, verbose_name='Tipo de Contrato')),
                ('justification_atipico', models.TextField(blank=True, null=True, verbose_name='Justificativa (se Atípico)')),
                ('security_deposit_months', models.PositiveIntegerField(default=3, verbose_name='Meses de Caução')),
                ('security_deposit_payment_type', models.CharField(choices=[('VISTA', 'À Vista'), ('PARCELADO', 'Parcelado')], max_length=20, verbose_name='Forma de Pagamento da Caução')),
                ('maintenance_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa de Manutenção')),
                ('water_billing_type', models.CharField(choices=[('INCLUSO', 'Incluso no Aluguel'), ('FIXO', 'Valor Fixo'), ('CONTA', 'Conta Individual')], max_length=20, verbose_name='Cobrança de Água')),
                ('water_description', models.CharField(blank=True, max_length=255, verbose_name='Descrição Água')),
                ('power_billing_type', models.CharField(choices=[('INCLUSO', 'Incluso no Aluguel'), ('FIXO', 'Valor Fixo'), ('CONTA', 'Conta Individual')], max_length=20, verbose_name='Cobrança de Energia')),
                ('power_description', models.CharField(blank=True, max_length=255, verbose_name='Descrição Energia')),
                ('testemunha1_cpf', models.CharField(max_length=14, verbose_name='CPF Testemunha 1')),
                ('testemunha2_cpf', models.CharField(max_length=14, verbose_name='CPF Testemunha 2')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
