# Generated by Django 5.2.11 on 2026-02-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='signature_city',
            field=models.CharField(default='Rio de Janeiro', max_length=100, verbose_name='Cidade da Assinatura'),
        ),
        migrations.AddField(
            model_name='contract',
            name='testemunha1_name',
            field=models.CharField(default='', max_length=255, verbose_name='Nome Testemunha 1'),
        ),
        migrations.AddField(
            model_name='contract',
            name='testemunha2_name',
            field=models.CharField(default='', max_length=255, verbose_name='Nome Testemunha 2'),
        ),
    ]
