# Generated by Django 5.2.11 on 2026-02-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_signature_city_contract_testemunha1_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='water_billing_type',
            field=models.CharField(choices=[('INCLUSO', 'Incluso no Aluguel'), ('FIXO', 'Valor Fixo')], max_length=20, verbose_name='Cobrança de Água'),
        ),
    ]
