# Generated by Django 5.2.11 on 2026-02-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contract_water_billing_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='power_description',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='water_description',
        ),
        migrations.AddField(
            model_name='contract',
            name='power_fixed_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Fixo Energia'),
        ),
        migrations.AddField(
            model_name='contract',
            name='water_fixed_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Fixo Água'),
        ),
    ]
