# Generated by Django 5.2.11 on 2026-02-11 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_currency_fields_for_water_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente de Análise'), ('APPROVED', 'Aprovado/Finalizado'), ('REJECTED', 'Rejeitado')], default='PENDING', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='locadora_cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF da Locadora'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='locadora_endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço da Locadora'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='locadora_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Locadora'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='locadora_rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG da Locadora'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='monthly_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Mensal'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='property_address',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço do Imóvel'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='property_cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP do Imóvel'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='security_deposit_payment_type',
            field=models.CharField(choices=[('VISTA', 'À Vista')], default='VISTA', max_length=20, verbose_name='Forma de Pagamento da Caução'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contract_docs/', verbose_name='Arquivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contracts.contract')),
            ],
        ),
    ]
