# Generated by Django 5.2.11 on 2026-03-01 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_contract_status_alter_contract_locadora_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='inspection_photos/', verbose_name='Foto de Vistoria')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_photos', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Foto de Vistoria',
                'verbose_name_plural': 'Fotos de Vistoria',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
