# Generated by Django 5.2.11 on 2026-03-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_inspectionphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='security_deposit_fixed_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Fixo da Garantia'),
        ),
        migrations.AddField(
            model_name='contract',
            name='security_deposit_type',
            field=models.CharField(choices=[('PROPORCIONAL', 'Proporcional ao Aluguel'), ('FIXO', 'Valor Fixo')], default='PROPORCIONAL', max_length=20, verbose_name='Tipo de Cálculo da Garantia'),
        ),
    ]
