# Generated by Django 5.2.11 on 2026-03-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_contract_security_deposit_fixed_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='security_deposit_months',
            field=models.PositiveIntegerField(blank=True, default=3, null=True, verbose_name='Meses de Caução'),
        ),
    ]
